// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZ02sc8WsIDi98A8ARp0MQsyhNsvc61Q',
    appId: '1:455198085978:web:5ac477e8e7734429739963',
    messagingSenderId: '455198085978',
    projectId: 'sikker-cykel',
    authDomain: 'sikker-cykel.firebaseapp.com',
    storageBucket: 'sikker-cykel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdrUmMJlVWTK3dETdPKbLk9jwhwdrjXE',
    appId: '1:455198085978:android:c6e356ae39da6f37739963',
    messagingSenderId: '455198085978',
    projectId: 'sikker-cykel',
    storageBucket: 'sikker-cykel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODf2a9OiiYHKqhAc28v9yclcIxhFXSDk',
    appId: '1:455198085978:ios:e17507d434f3b574739963',
    messagingSenderId: '455198085978',
    projectId: 'sikker-cykel',
    storageBucket: 'sikker-cykel.appspot.com',
    iosBundleId: 'com.example.sikkerCykel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODf2a9OiiYHKqhAc28v9yclcIxhFXSDk',
    appId: '1:455198085978:ios:e17507d434f3b574739963',
    messagingSenderId: '455198085978',
    projectId: 'sikker-cykel',
    storageBucket: 'sikker-cykel.appspot.com',
    iosBundleId: 'com.example.sikkerCykel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSZ02sc8WsIDi98A8ARp0MQsyhNsvc61Q',
    appId: '1:455198085978:web:ba00a67450316a05739963',
    messagingSenderId: '455198085978',
    projectId: 'sikker-cykel',
    authDomain: 'sikker-cykel.firebaseapp.com',
    storageBucket: 'sikker-cykel.appspot.com',
  );
}
